var data = {
    categories: ['Action', 'Animation', 'Comedy', 'Horror / Thriller'],
    max_rating: 5,
    films: [{
        src: 'TIE+Fighter+-+short+film(720p).mp4',
        title: 'TIE Fighter',
        duration: '7:27',
        author: 'OtaKing77077',
        author_url: 'https://www.youtube.com/channel/UCRBNWKYrybXl2Un6-ejwx8g',
        description: 'That if there was an Empire-focussed short Star Wars animation, drawn with the crazy detail and shading of classic 80s anime that\'s all but vanished from Japan nowadays? <br /> Well, I tried my best. Apologies in advance for not living up to Venus Wars standards. <br /> Drawn and animated by yours truly over 4 years\' worth of weekends, with music by the living guitar solo Zak Rahman and sound design by up and coming audio technician Joseph Leyva. Fans of Lucasarts\' seminal 1994 TIE Fighter game may notice a few familiar sights and sounds. That “incoming missile” noise gives me horrible flashbacks to this day...',
        year: 2015,
        audio_language: 'N/A',
        sub_language: 'N/A',
        rating: 4,
        category: 'Animation',
        img: 'img/animation/thefighter.jpg'
    }, {
        src: 'Naruto+Live+Action+(avec+Florian+Nguyen+et+Aziatomik)(720p).mp4',
        title: 'Naruto Live Action',
        duration: '1:47',
        author: 'Brice Duan',
        author_url: 'https://www.youtube.com/channel/UCYF-3u_Jh5lWzPG2gRDD3-Q',
        description: 'A member of the Akatsuki came to challenge the heirs of Naruto! This is a movie fan honoring the work of Masashi Kishimito. Thanks to Rivenx3i for inspiring me with his video Naruto Shippuden Dreamers Fight, the best movie fan about Naruto to date.',
        year: 2013,
        audio_language: 'French',
        sub_language: 'N/A',
        rating: 3,
        category: 'Action',
        img: 'img/action/narutoliveaction.jpg'
    }, {
        src: 'Dragon+Ball+vs+Naruto.+Anime+fight.(720p).mp4',
        title: 'Dragon Ball vs Naruto. Anime fight',
        duration: '8:39',
        author: 'Alberto Barberá',
        author_url: 'https://www.youtube.com/channel/UCaH3HAq1O9rJvTUn0mlVVkw',
        description: 'Brutal fight with a touch of humor and comedy. The idea came up playing the Dragon Ball Xenoverse after reading the Naruto Shippuden manga while I became Super Saiyan and listened to the rap of Naruto and Sasuke. Love Dragon Ball games. <br /> Waiting for Naruto Gaiden to come soon... While we enjoy DB Super.',
        year: 2015,
        audio_language: 'N/A',
        sub_language: 'N/A',
        rating: 5,
        category: 'Action',
        img: 'img/action/narutovsdbz.jpg'
    }, {
        src: 'Naruto+Shippuden_+Dance+of+War+-+Short+Film+(Turn+On+Subtitles)(1080p).mp4',
        title: 'Naruto Shippuden: Dance of War',
        duration: '7:48',
        author: 'RivenX3i',
        author_url: 'https://www.youtube.com/channel/UC-Op8pOVwbeqp6lyL2xJvqQ',
        description: 'The 4th Great Ninja War is near. Two Hidden Leaf ninja say goodbye to where they grew into ninja, by holding a ceremony to test their own resolve.',
        year: 2015,
        audio_language: 'Japanese',
        sub_language: 'N/A',
        rating: 4,
        category: 'Action',
        img: 'img/action/narutodanceofwar.jpg'
    }, {
        src: 'NARUTO+-+New+Movie+2018+-+Full+Trailer+AMAZING!!(720p).mp4',
        title: 'Naruto fan trailer 2018',
        duration: '12:50',
        author: 'RivenX3i',
        author_url: 'https://www.youtube.com/channel/UC-Op8pOVwbeqp6lyL2xJvqQ',
        description: 'The 4th Great Ninja War is near. Two Hidden Leaf ninja say goodbye to where they grew into ninja, by holding a ceremony to test their own resolve.',
        year: 2016,
        audio_language: 'Japanese',
        sub_language: 'N/A',
        rating: 3,
        category: 'Action',
        img: 'img/action/narutonewfilm.jpg'
    }, {
        src: 'Naruto+The+Movie!+(Official+Fake+Trailer)(720p).mp4',
        title: 'Naruto, The Movie!',
        duration: '3:15',
        author: 'nigahiga',
        author_url: 'https://www.youtube.com/channel/UCSAUGyc_xA8uYzaIVG6MESQ',
        description: 'Huge THANK YOU to Portal A, Gritty Reboots and everyone on the Japan team for helping out with this! #grubblife',
        year: 2013,
        audio_language: 'English',
        sub_language: 'N/A',
        rating: 3,
        category: 'Comedy',
        img: 'img/comedy/narutothemovie.jpg'
    }, {
        src: 'Red+Hood_+The+Fallen+-+DC+Comic+Batman+Fan+Film(720p).mp4',
        title: 'Red Hood: The Fallen',
        duration: '23:16',
        author: 'Toby Bajrovic',
        author_url: 'https://www.youtube.com/channel/UCjGUxyIEtqh_CyWBIVIhzng',
        description: 'Red Hood: The Fallen is a fan made DC Comic film produced in Perth, Western Australia.',
        year: 2015,
        audio_language: 'English',
        sub_language: 'N/A',
        rating: 5,
        category: 'Action',
        img: 'img/action/redhoodthefallen.jpg'
    }, {
        src: 'JUSTICE+LEAGUE_+Trinity+Force+_+DC+FAN+FILM+_(720p).mp4',
        title: 'JUSTICE LEAGUE: Trinity Force',
        duration: '16:29',
        author: 'SHIELDS Productions',
        author_url: 'https://www.youtube.com/channel/UCaz9yZYvDvbG_mgPhcCn4pw',
        description: 'Four months after an earth shattering event, Broken, The Justice League must put their differences aside to stop The Joker!',
        year: 2015,
        audio_language: 'English',
        sub_language: 'N/A',
        rating: 2.5,
        category: 'Action',
        img: 'img/action/justiceleaguetrinityforce.jpg'
    }, {
        src: 'The+Mad+Hatter+-+Fan+Film(720p).mp4',
        title: 'The Mad Hatter',
        duration: '6:16',
        author: 'Wolfspider Productions',
        author_url: 'https://www.youtube.com/channel/UC_BAlJSUbpqzSjNX8on3Rgw',
        description: 'A dark modern interpretation on the DC comic villain, Jervis Tetch aka The Mad Hatter. Set in the time of the modern interpretations on Alice in Wonderland.',
        year: 2016,
        audio_language: 'N/A',
        sub_language: 'N/A',
        rating: 2,
        category: 'Horror',
        img: 'img/horror/themadhater.jpg'
    }, {
        src: 'The+Flash+Lite+(comedy+fan+film)(720p).mp4',
        title: 'The Flash Lite',
        duration: '10:14',
        author: 'The Chublin Brothers',
        author_url: 'https://www.youtube.com/channel/UCPFmTZlrfUkRCjGgSLtqx1g',
        description: 'A world-class athlete, but otherwise ordinary guy, assumes the identity of The Flash after being named the "Fastest Man Alive."  But will being slightly faster than everyone else, with exactly zero superpowers, give him the crime-fighting edge he needs?',
        year: 2013,
        audio_language: 'English',
        sub_language: 'N/A',
        rating: 4,
        category: 'Comedy',
        img: 'img/comedy/theflashlite.jpg'
    }, {
        src: 'Clash+at+the+Cantina+(2014)+-+Star+Wars+Fan+Film(720p).mp4',
        title: 'Clash at the Cantina',
        duration: '4:45',
        author: 'Corey Vidal',
        author_url: 'https://www.youtube.com/channel/UCRBNWKYrybXl2Un6-ejwx8g',
        description: 'As part of the on-going Star Wars-inspired action comedy video series between YouTubers Corey Vidal (ApprenticeA) and Craig Benzine (Wheezy Waiter), the guys take the battle to the Cantina with a new lightsaber fight.',
        year: 2014,
        audio_language: 'English',
        sub_language: 'N/A',
        rating: 4,
        category: 'Comedy',
        img: 'img/comedy/clashatthecantina.jpg'
    }, {
        src: 'THE+74th+HUNGER+GAMES+(SHORT+COMEDY+FAN+FILM)(720p).mp4',
        title: 'THE 74th HUNGER GAMES',
        duration: '4:24',
        author: 'ChickenFeetFilms',
        author_url: 'https://www.youtube.com/channel/UC9nzWgRq-cQcakkzZq1XZvg',
        description: 'A short "HUNGER GAMES" fan film, made by ChickenFeetFilms. <br /> Music provided by boyinaband.com http://bit.ly/PLrd1Y',
        year: 2012,
        audio_language: 'English',
        sub_language: 'N/A',
        rating: 2,
        category: 'Comedy',
        img: 'img/comedy/the74hungergames.jpg'
    }, {
        src: 'VICTIM+-+A+Short+Slender+Man+Horror+Film(720p).mp4',
        title: 'VICTIM',
        duration: '14:30',
        author: 'Eddie Adamson',
        author_url: 'https://www.youtube.com/channel/UCpWweEWZIfalXgKS1xO2RDw',
        description: 'This is a Short Horror film I made for my last college project in Creative Media Production, before I went off to University. We were given the chance to individually make a film of our own choice, of varied length and subject matter.',
        year: 2013,
        audio_language: 'N/A',
        sub_language: 'N/A',
        rating: 4,
        category: 'Horror',
        img: 'img/horror/victim.jpg'
    }, {
        src: 'T+MOVE+-+A+Short+Horror+Film+(2017)(720p).mp4',
        title: 'FALLOUT',
        duration: '7:27',
        author: 'AndrewProductionsTV',
        author_url: 'https://www.youtube.com/channel/UCOAHgaVjyUjFtxhgCAQ_vAg',
        description: '►FALLOUT -  Apocalyptic Thriller Short Film <br /> Aaron, a young researcher seeks to discover the deadly disease that plagues Earth. This project is meant to convey the philosophical message that Humans are the deadliest beings to ever walk the Earth through Industrialism, Animal Cruelty/Exploitation, and War. ',
        year: 2015,
        audio_language: 'N/A',
        sub_language: 'N/A',
        rating: 3,
        category: 'Horror',
        img: 'img/horror/dontmoove.jpg'
    }, {
        src: 'Dragon+Ball+Z_+Light+of+Hope+-+Pilot(720p).mp4',
        title: 'Dragon Ball Z: Light of Hope - Pilot',
        duration: '13:14',
        author: 'RobotUnderdog2',
        author_url: 'https://www.youtube.com/channel/UCkeLPTcjQm3zlPuDdvS4gvg',
        description: 'This series is an adaptation of “The History of Trunks” TV Special. In this timeline, Goku & the other Z Warriors are dead. This is the story of Gohan & Trunks in their battle to survive against the Androids.',
        year: 2015,
        audio_language: 'English',
        sub_language: 'N/A',
        rating: 4,
        category: 'Action',
        img: 'img/action/dbzlightofhope.jpg'
    }, {
        src: 'Attack+on+Titan+-+LEVI+vs+BEAST+TITAN+-+Fan+made+animation+-+Shingeki+no+kyojin+manga+chapter+81(480p).mp4',
        title: 'Attack on Titan - LEVI vs BEAST TITAN',
        duration: '1:14',
        author: 'S.L.H Animation',
        author_url: 'https://www.youtube.com/channel/UCE6CEl3ZoiDLUhawFG5xn1g',
        description: 'It is a fan made animation of Attack on Titan. It was for fun and I do not own right to Attack in Titan. All credit go to WIT studio, Production I.G, and Hajime Isayama for such amazing series.',
        year: 2017,
        audio_language: 'N/A',
        sub_language: 'N/A',
        rating: 4,
        category: 'Animation',
        img: 'img/animation/Attackontitan.jpg'
    }, {
        src: 'Chinese+teenager+created+awesome+fight+scene+animation(536p).mp4',
        title: 'Personal Animated Short',
        duration: '3:50',
        author: 'magnil',
        author_url: 'https://www.youtube.com/channel/UCRBNWKYrybXl2Un6-ejwx8g',
        description: 'Chinese 19-year-old student-produced personal animated short "high temperature vs exclusion"; Concepts, animations, backgrounds, compositions are done by the author personally.',
        year: 2015,
        audio_language: 'N/A',
        sub_language: 'N/A',
        rating: 5,
        category: 'Animation',
        img: 'img/animation/chineseteenager.jpg'
    }, {
        src: 'SPAWN_+THE+RECALL+-+FAN+FILM(720p).mp4',
        title: 'SPAWN: THE RECALL',
        duration: '7:56',
        author: 'Irissee',
        author_url: 'https://www.youtube.com/channel/UCefxt5RuoiBlanGXmh4vg_A',
        description: 'SPAWN : THE RECALL is the story of a former witch and her son, who try to live a normal life away from the darkness.',
        year: 2014,
        audio_language: 'English',
        sub_language: 'N/A',
        rating: 4,
        category: 'Horror',
        img: 'img/horror/spawntherecall.jpg'
    }, {
        src: '[Rebeler]+Madara+VS+Hashirama+-+Cosplay+Movie(720p).mp4',
        title: 'Madara VS Hashirama',
        duration: '8:06',
        author: 'Rebeler Team',
        author_url: 'https://www.youtube.com/channel/UCSDJAB-afLRrbytxQuq-lAg',
        description: 'REBEL is an Independent Cosplay Organization in the form of Team in Bojonegoro - East Java, which has a goal to develop the creativity of its members in the world of percosplayan.',
        year: 2016,
        audio_language: 'N/A',
        sub_language: 'N/A',
        rating: 4,
        category: 'Action',
        img: 'img/action/madara.jpg'
    },
    ]
};
